/**
 * Shared types for the DesiOffers Guides AI authoring workflow.
 *
 * These types define the structured data objects that Antigravity
 * (the AI orchestration layer) passes into deterministic project utilities.
 *
 * IMPORTANT: No LLM or AI reasoning lives in this file or in any module
 * that imports it. All logic here is purely data-structure definition.
 */

// ---------------------------------------------------------------------------
// Article Types
// ---------------------------------------------------------------------------

export type ArticleType =
  | 'buying-guide'
  | 'best-products'
  | 'comparison'
  | 'how-to-choose'
  | 'gift-guide'
  | 'deal-guide';

export type PriceVerificationState = 'verified' | 'unknown' | 'user-observed';
export type AvailabilityVerificationState = 'verified' | 'unknown';

// ---------------------------------------------------------------------------
// Image Source and Rights — Media Rights Terminology
//
// AI-generated:    source = 'ai-generated',  rightsStatus = 'original'
// User-provided:   source = 'user-provided', rightsStatus = 'needs-review' (unless confirmed)
// Licensed:        source = 'licensed',       rightsStatus = 'authorized'
// Restricted:      rightsStatus = 'restricted' → publication MUST be blocked
// ---------------------------------------------------------------------------

export type ImageSource =
  | 'ai-generated'   // Generated by Antigravity; we own the output
  | 'user-provided'  // Uploaded by owner; review required
  | 'licensed'       // Explicitly licensed for use
  | 'amazon-api'     // Reserved for future Creators API (currently disabled)
  | 'r2'             // Stored in R2 (used for any owned/editorial image)
  | 'none';          // No image — use imageless layout

export type ImageRightsStatus =
  | 'original'      // AI-generated editorial; we own it
  | 'authorized'    // Licensed/explicitly permitted
  | 'needs-review'  // Uploaded; not yet confirmed by human
  | 'restricted';   // Must NEVER be published

export type HeroImageStatus =
  | 'ready'              // Image is in R2, confirmed
  | 'needs-generation'   // Brief exists, no image yet — blocks publication
  | 'fallback-approved'; // Human has explicitly approved using fallback

export type ImageVariantRole =
  | 'thumbnail'
  | 'card'
  | 'medium'
  | 'article'
  | 'hero'
  | 'social';

// ---------------------------------------------------------------------------
// Article Draft — structured input to article-builder.ts
// ---------------------------------------------------------------------------

export interface ProductDraft {
  position: number;
  name: string;
  brand: string;
  model?: string;
  asin?: string;
  /** R2 key or empty string. When imageSource is 'none', this is ignored. */
  image: string;
  imageAlt: string;
  imageSource: ImageSource;
  imageRightsStatus?: ImageRightsStatus;
  editorialBadge?: string;
  shortDescription: string;
  bestFor: string;
  pros: string[];
  cons: string[];
  priceDisplay?: string;
  priceObservedAt?: string;
  priceVerification?: PriceVerificationState;
  availabilityNote?: string;
  availabilityVerification?: AvailabilityVerificationState;
  affiliateUrl: string;
  researchNote?: string;
}

export interface QuickPickDraft {
  badge: string;
  name: string;
  asin?: string;
  affiliateUrl: string;
  priceDisplay?: string;
}

export interface FaqItem {
  question: string;
  answer: string;
}

export interface ArticleDraft {
  // Identity
  title: string;
  slug: string;
  description: string;
  articleType: ArticleType;

  // Dates (ISO 8601 strings)
  publishedDate: string;
  updatedDate?: string;
  lastVerified: string;

  // Verification flags
  productDataVerified: boolean;
  priceVerified: boolean;
  availabilityVerified: boolean;

  // Taxonomy — all must be validated by taxonomy-resolver before builder runs
  author: string; // slug
  category: string; // slug
  subcategory?: string; // slug
  tags: string[]; // slugs, max 6

  // Hero image
  heroImage: string; // R2 key or empty string
  heroImageAlt: string;
  heroImageStatus: HeroImageStatus;
  heroImageSource?: ImageSource;
  heroImageRightsStatus?: ImageRightsStatus;

  // Metadata
  featured: boolean;
  affiliateDisclosure?: string;
  readingTime?: number;
  seoTitle?: string;
  seoDescription?: string;

  // Always true on initial draft — never auto-published
  draft: true;

  // Content
  quickPicks?: QuickPickDraft[];
  products: ProductDraft[];
  faq?: FaqItem[];
  sources?: string[];

  // Body sections — Antigravity provides the text; builder serializes it
  bodySections: BodySection[];
}

export interface BodySection {
  type:
    | 'intro'
    | 'methodology'
    | 'quick-picks-intro'
    | 'product-section'
    | 'buying-factors'
    | 'comparison-table'
    | 'faq-section'
    | 'verdict'
    | 'custom';
  heading?: string;
  content: string; // Markdown string
}

// ---------------------------------------------------------------------------
// Taxonomy Resolution
// ---------------------------------------------------------------------------

export interface ResolvedTaxonomy {
  category: string; // validated slug
  subcategory?: string; // validated slug
  tags: string[]; // validated slugs
  warnings: string[];
}

export interface TaxonomyResolutionResult {
  resolved?: ResolvedTaxonomy;
  needsClarification: boolean;
  /** Human-readable question to present if needsClarification is true */
  clarificationQuestion?: string;
  errors: string[];
}

export interface CategoryData {
  name: string;
  slug: string;
  description: string;
  icon: string;
  color: string;
}

export interface SubcategoryData {
  name: string;
  slug: string;
  category: string; // parent category slug
  description: string;
}

export interface TagData {
  name: string;
  slug: string;
  description: string;
  status: 'active' | 'deprecated' | 'merged';
  mergedIntoSlug?: string;
}

export interface AuthorData {
  name: string;
  slug: string;
  gender?: 'male' | 'female';
  role?: string;
  bio?: string;
  avatar?: string;
}

// ---------------------------------------------------------------------------
// Image Brief — output of image-brief.ts, consumed by Antigravity
// ---------------------------------------------------------------------------

export type ImageBriefType = 'AI_EDITORIAL' | 'CATEGORY_ART';

export interface ImageBrief {
  type: ImageBriefType;
  /** Full descriptive generation prompt */
  prompt: string;
  /** Always includes: no logos, no text, no specific product model, no branding */
  negativePrompt: string;
  targetWidth: number;
  targetHeight: number;
  aspectRatio: string;
  /** Draft alt text — Antigravity may refine */
  altDraft: string;
  variant: ImageVariantRole;
  /** AI-generated editorial imagery is always 'original' rights */
  rightsStatus: Extract<ImageRightsStatus, 'original'>;
  /** Article or category slug this image belongs to */
  contextSlug: string;
}

// ---------------------------------------------------------------------------
// Quality Guard
// ---------------------------------------------------------------------------

export interface QualityWarning {
  severity: 'error' | 'warning';
  message: string;
  /** The offending phrase or pattern that triggered the warning */
  trigger: string;
  /** Suggested replacement or action */
  suggestion: string;
}

// ---------------------------------------------------------------------------
// SEO
// ---------------------------------------------------------------------------

export interface SeoResult {
  slug: string;
  seoTitle: string;
  seoDescription: string;
  warnings: string[];
}
